version: '1'
services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - short_url
    depends_on:
      - redis
      - db
    container_name: backend-short-url

  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - short_url
    container_name: redis

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /data/postgres
    volumes:
      -postgres:data/postgres
    ports:
      -"5432:5432"
    networks:
      - short_url
    container_name: dbShortUrl
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  frontend:
    expose:
      - 3000
    environment:
      - baserUrl: ${baserUrl:-server:8080/}
    container_name: frontend-short-url
    networks:
      - short_url

networks:
  short_url: